-   id: absolufy-imports
    name: absolufy-imports
    description: Automatically convert relative imports to absolute
    entry: absolufy-imports
    language: python
    types_or: [python, pyi]
    minimum_pre_commit_version: 2.9.2
